#!/bin/sh

# Function definitions #################################################

usage()
{
  echo "Usage: notes [OPTION]...

  -c		Compile notes
  -e [date] 	Edit note in $EDITOR
  -r [date]	Read note in $PAGER

  Default: notes -e 
  Note that date defaults to today
  "
  exit 2
}

set_variable()
{
  local varname=$1
  shift
  if [ -z "${!varname}" ]; then
    eval "$varname=\"$@\""
  else
    echo "Error: $varname already set"
    usage
  fi
}

initialize()
{
# Check if XDG_CONFIG_HOME is set (may use for configuration in future)
#if [ -z $XDG_CONFIG_HOME ]
#then
#	echo "Warning: XDG_CONFIG_HOME is not set. Assuming $HOME/.config"
#	XDG_CONFIG_HOME=$HOME/.config
#fi

# Definitions
notesdir=$HOME/notes

# Check if notes directory exists
if [ ! -d $notesdir ]
then
	echo "Notes directory does not yet exist."
	echo "Creating $notesdir"
	mkdir $notesdir
fi
}

edit_note()
{
initialize

today=`date +%Y%m%d`
notefile=$notesdir/$today

# Check if note already exists
if [ -f $notefile ]
then
	$EDITOR $notefile
	exit 0
else
	touch $notefile
	$EDITOR $notefile
	exit 0
fi
}

read_note()
{
initialize

today=`date +%Y%m%d`
notefile=$notesdir/$today

# Check if note already exists
if [ -f $notefile ]
then
	$PAGER $notefile
	exit 0
else
	echo "Error: note $notefile does not exist"
	exit 1
fi
}

#TODO
compile()
{
	echo "compiling notes"
	exit 0
}

# Main script ##########################################################

# Parse input

while getopts 'cerh' c
do
	case $c in
		c) compile ;;
		e) edit_note ;;
		r) read_note ;;
		h) usage ;;
	esac
done

# If no arguments are passed, assume `notes -e`
edit_note
